#Exception handling:
when there is exception does not want intruction/disturbance exception in the flow,to achive this exception in the handling.

#
a=100
b=0
try:#u r telling this may have error,u try
    print(a/b)
#except exception:#u saying if error  the i handle
#print("cant divide any number by zero")
except Exception as e:
    print("please note,number cant be divided by zero",e)
    print("bye")
    
#
a=4
b=3
try:
    print("resource open")
    print(a/b)
except Exception is e:
    print("dont give second no.as error",e)
finally:#will get executed if there is error or not)
    print("resource closed")


#for those specific error only those exception
#blpocks will get executed
a=10
try:
    b=int(input("enter the number"))
    print(" welcome")
    print(a/b)
except zerodivisionError as e:
        print("please note, number cant be divided by zero:",e)
except valueError as e:
        print("invalid input",e)
except Exception as e:#if not any above errors
        print("other error",e)
finally :
        print(" bye")
# 
#raise used to interrupt

x=48
if x%2!=0:
    raise Exception ("x should be even number")
else:
    print("x is even number. correct")
